// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bkqemzkgoauiztxnfbaf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJrcWVtemtnb2F1aXp0eG5mYmFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwNjU3MDksImV4cCI6MjA1ODY0MTcwOX0.s_kDmQdOmK-lbX5WSBdUsIKuAnDk8m2Q-LPXUAzQyrI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);